# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hafez_telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='changedUserTime',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین استفاده از ربات'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='createdUserTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ساخت اکانت'),
            preserve_default=False,
        ),
    ]
